In [ ]:
!pip install tensorflow-gpu

Collecting tensorflow-gpu
  Downloading tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_parquet("/content/predictive_maintenance_log_v5_featured.parquet")

In [ ]:
df.shape

(460672, 37)

In [ ]:
df.head()

,PrinterID,ReferenceDate,log_alert_count_3m,log_warning_alert_count_3m,log_critical_alert_count_3m,unique_alert_codes_3m,log_alert_count_1m,log_warning_alert_count_1m,log_critical_alert_count_1m,unique_alert_codes_1m,...,critical_x_service_history,log_job_volume_3m,log_color_job_volume_3m,log_bw_job_volume_3m,log_job_volume_1m,job_growth_ratio,days_since_last_service,service_count_1yr,is_neglected,ServiceRequiredNext_30_Days
0,4da956db-a9bd-490c-8570-0a18c3fcb2f0,2025-07-01,5.463832,5.446737,1.609438,11.0,4.744932,4.736198,0.693147,6.0,...,0.0,7.594381,7.259820,6.318968,7.594381,1.0,530,0,1,0
1,0eb0bdd6-0308-4a0b-9c06-c8b1d6f5b171,2025-07-01,5.075174,5.017280,2.302585,12.0,4.025352,4.025352,0.000000,4.0,...,36.0,5.225747,4.605170,3.737670,5.225747,1.0,49,4,0,0
2,c4c7a34a-3130-4320-9eaf-7c11c0cc0f0d,2025-07-01,4.691348,4.682131,0.693147,5.0,4.204693,4.189655,0.693147,3.0,...,5.0,6.001415,0.000000,6.001415,6.001415,1.0,292,5,0,0
3,3b1c643d-0adc-4f34-972a-60d8cc7e5cbb,2025-07-01,4.430817,0.000000,3.637586,9.0,4.430817,0.000000,3.637586,9.0,...,185.0,4.624973,0.000000,4.624973,4.624973,1.0,25,5,0,1
4,5de0fc8d-3cee-4058-bf2f-47273d9766d6,2025-07-01,3.610918,2.995732,2.890372,11.0,2.995732,2.397895,2.302585,5.0,...,0.0,7.389564,5.950643,6.744059,7.389564,1.0,886,0,1,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460672 entries, 0 to 460671
Data columns (total 37 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   PrinterID                     460672 non-null  object
 1   ReferenceDate                 460672 non-null  datetime64[us]
 2   log_alert_count_3m            460672 non-null  float64
 3   log_warning_alert_count_3m    460672 non-null  float64
 4   log_critical_alert_count_3m   460672 non-null  float64
 5   unique_alert_codes_3m         460672 non-null  float64
 6   log_alert_count_1m            460672 non-null  float64
 7   log_warning_alert_count_1m    460672 non-null  float64
 8   log_critical_alert_count_1m   460672 non-null  float64
 9   unique_alert_codes_1m         460672 non-null  float64
 10  critical_ratio_3m             460672 non-null  float64
 11  critical_ratio_1m             460672 non-null  float64
 12  warning_ratio_3m              460672 non-null  float64
 13  warning_ratio_1m              460672 non-null  float64
 14  alert_growth_ratio            460672 non-null  float64
 15  total_alert_intensity         460672 non-null  float64
 16  alert_intensity_3m            460672 non-null  float64
 17  alert_intensity_1m            460672 non-null  float64
 18  critical_intensity_3m         460672 non-null  float64
 19  warning_intensity_1m          460672 non-null  float64
 20  warning_intensity_3m          460672 non-null  float64
 21  critical_intensity_1m         460672 non-null  float64
 22  alert_spike                   460672 non-null  float64
 23  warning_spike                 460672 non-null  float64
 24  critical_spike                460672 non-null  float64
 25  warning_to_critical_ratio_1m  460672 non-null  float64
 26  critical_ratio_change         460672 non-null  float64
 27  critical_x_service_history    460672 non-null  float64
 28  log_job_volume_3m             460672 non-null  float64
 29  log_color_job_volume_3m       460672 non-null  float64
 30  log_bw_job_volume_3m          460672 non-null  float64
 31  log_job_volume_1m             460672 non-null  float64
 32  job_growth_ratio              460672 non-null  float64
 33  days_since_last_service       460672 non-null  int64
 34  service_count_1yr             460672 non-null  int64
 35  is_neglected                  460672 non-null  int32
 36  ServiceRequiredNext_30_Days   460672 non-null  int32
dtypes: datetime64[us](1), float64(31), int32(2), int64(2), object(1)
memory usage: 126.5+ MB

In [ ]:
df.describe()

,ReferenceDate,log_alert_count_3m,log_warning_alert_count_3m,log_critical_alert_count_3m,unique_alert_codes_3m,log_alert_count_1m,log_warning_alert_count_1m,log_critical_alert_count_1m,unique_alert_codes_1m,critical_ratio_3m,...,critical_x_service_history,log_job_volume_3m,log_color_job_volume_3m,log_bw_job_volume_3m,log_job_volume_1m,job_growth_ratio,days_since_last_service,service_count_1yr,is_neglected,ServiceRequiredNext_30_Days
count,460672,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,...,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000,460672.000000
mean,2025-06-03 08:09:14.153931,5.567226,5.167209,2.811992,13.000289,5.013376,4.627168,2.277011,7.315734,0.145023,...,576.366547,3.849110,2.198609,3.574652,3.603980,0.317742,399.905230,5.372308,0.299456,0.141723
min,2021-02-01 00:00:00,0.693147,0.000000,0.000000,1.000000,0.693147,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,2025-03-01 00:00:00,4.672829,4.189655,1.791759,8.000000,4.143135,3.637586,1.098612,5.000000,0.017123,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,60.000000,0.000000,0.000000,0.000000
50%,2025-06-01 00:00:00,5.826000,5.549076,2.833213,12.000000,5.273000,5.003946,2.197225,7.000000,0.057151,...,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000,173.000000,2.000000,0.000000,0.000000
75%,2025-09-01 00:00:00,6.647688,6.473891,3.828641,18.000000,6.059123,5.891644,3.258097,10.000000,0.181495,...,210.000000,8.371705,5.049856,7.756195,7.852828,0.675797,445.000000,7.000000,1.000000,0.000000
max,2025-11-01 00:00:00,11.837759,10.760983,10.787090,54.000000,11.158434,10.320387,10.356790,29.000000,1.000000,...,518336.000000,14.183160,12.849349,13.801816,13.967147,1.000000,9999.000000,178.000000,1.000000,1.000000
std,NaN,1.582771,1.838688,1.524608,7.060620,1.547441,1.771995,1.442466,3.642700,0.205007,...,3585.801639,4.385804,3.327818,4.126827,4.141441,0.407322,963.522243,7.754720,0.458020,0.348767

In [ ]:
df.columns

Index(['PrinterID', 'ReferenceDate', 'log_alert_count_3m',
       'log_warning_alert_count_3m', 'log_critical_alert_count_3m',
       'unique_alert_codes_3m', 'log_alert_count_1m',
       'log_warning_alert_count_1m', 'log_critical_alert_count_1m',
       'unique_alert_codes_1m', 'critical_ratio_3m', 'critical_ratio_1m',
       'warning_ratio_3m', 'warning_ratio_1m', 'alert_growth_ratio',
       'total_alert_intensity', 'alert_intensity_3m', 'alert_intensity_1m',
       'critical_intensity_3m', 'warning_intensity_1m', 'warning_intensity_3m',
       'critical_intensity_1m', 'alert_spike', 'warning_spike',
       'critical_spike', 'warning_to_critical_ratio_1m',
       'critical_ratio_change', 'critical_x_service_history',
       'log_job_volume_3m', 'log_color_job_volume_3m', 'log_bw_job_volume_3m',
       'log_job_volume_1m', 'job_growth_ratio', 'days_since_last_service',
       'service_count_1yr', 'is_neglected', 'ServiceRequiredNext_30_Days'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Target
y = df['ServiceRequiredNext_30_Days']

# Features
X = df.drop(columns=['ServiceRequiredNext_30_Days','PrinterID','ReferenceDate'])

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

model_ann = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model_ann.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(patience=5)

history = model_ann.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=256,
    callbacks=[early_stop]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 15s 9ms/step - accuracy: 0.8283 - loss: 0.3967 - val_accuracy: 0.8703 - val_loss: 0.3375
Epoch 2/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8694 - loss: 0.3406 - val_accuracy: 0.8707 - val_loss: 0.3356
Epoch 3/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8692 - loss: 0.3385 - val_accuracy: 0.8715 - val_loss: 0.3352
Epoch 4/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - accuracy: 0.8706 - loss: 0.3371 - val_accuracy: 0.8710 - val_loss: 0.3360
Epoch 5/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.8695 - loss: 0.3383 - val_accuracy: 0.8712 - val_loss: 0.3339
Epoch 6/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8716 - loss: 0.3363 - val_accuracy: 0.8717 - val_loss: 0.3349
Epoch 7/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8694 - loss: 0.3393 - val_accuracy: 0.8716 - val_loss: 0.3338
Epoch 8/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8710 - loss: 0.3356 - val_accuracy: 0.8714 - val_loss: 0.3341
Epoch 9/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8731 - loss: 0.3326 - val_accuracy: 0.8718 - val_loss: 0.3336
Epoch 10/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8714 - loss: 0.3353 - val_accuracy: 0.8718 - val_loss: 0.3332
Epoch 11/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8704 - loss: 0.3362 - val_accuracy: 0.8714 - val_loss: 0.3345
Epoch 12/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8710 - loss: 0.3349 - val_accuracy: 0.8721 - val_loss: 0.3328
Epoch 13/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8709 - loss: 0.3359 - val_accuracy: 0.8715 - val_loss: 0.3338
Epoch 14/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8702 - loss: 0.3361 - val_accuracy: 0.8715 - val_loss: 0.3336
Epoch 15/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8711 - loss: 0.3351 - val_accuracy: 0.8717 - val_loss: 0.3334
Epoch 16/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8728 - loss: 0.3320 - val_accuracy: 0.8718 - val_loss: 0.3332
Epoch 17/50
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8714 - loss: 0.3339 - val_accuracy: 0.8717 - val_loss: 0.3333

In [ ]:
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.models import Sequential

# reshape for RNN
X_train_rnn = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test_rnn = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))

model_rnn = Sequential([
    SimpleRNN(32, activation='tanh', input_shape=(1, X_train.shape[1])),
    Dense(1, activation='sigmoid')
])

model_rnn.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model_rnn.fit(
    X_train_rnn,
    y_train,
    epochs=30,
    batch_size=256,
    validation_split=0.2
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8254 - loss: 0.4231 - val_accuracy: 0.8698 - val_loss: 0.3402
Epoch 2/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8687 - loss: 0.3431 - val_accuracy: 0.8694 - val_loss: 0.3387
Epoch 3/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8691 - loss: 0.3412 - val_accuracy: 0.8704 - val_loss: 0.3371
Epoch 4/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8694 - loss: 0.3402 - val_accuracy: 0.8708 - val_loss: 0.3352
Epoch 5/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8700 - loss: 0.3391 - val_accuracy: 0.8708 - val_loss: 0.3354
Epoch 6/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8696 - loss: 0.3371 - val_accuracy: 0.8707 - val_loss: 0.3349
Epoch 7/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8697 - loss: 0.3384 - val_accuracy: 0.8712 - val_loss: 0.3350
Epoch 8/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8704 - loss: 0.3384 - val_accuracy: 0.8707 - val_loss: 0.3361
Epoch 9/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8698 - loss: 0.3378 - val_accuracy: 0.8707 - val_loss: 0.3351
Epoch 10/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8710 - loss: 0.3365 - val_accuracy: 0.8711 - val_loss: 0.3342
Epoch 11/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8698 - loss: 0.3388 - val_accuracy: 0.8707 - val_loss: 0.3361
Epoch 12/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8702 - loss: 0.3368 - val_accuracy: 0.8711 - val_loss: 0.3339
Epoch 13/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8698 - loss: 0.3378 - val_accuracy: 0.8711 - val_loss: 0.3341
Epoch 14/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8696 - loss: 0.3382 - val_accuracy: 0.8711 - val_loss: 0.3337
Epoch 15/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8711 - loss: 0.3355 - val_accuracy: 0.8715 - val_loss: 0.3342
Epoch 16/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8710 - loss: 0.3359 - val_accuracy: 0.8714 - val_loss: 0.3337
Epoch 17/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8700 - loss: 0.3372 - val_accuracy: 0.8709 - val_loss: 0.3338
Epoch 18/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8703 - loss: 0.3368 - val_accuracy: 0.8713 - val_loss: 0.3335
Epoch 19/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8704 - loss: 0.3366 - val_accuracy: 0.8715 - val_loss: 0.3335
Epoch 20/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8713 - loss: 0.3347 - val_accuracy: 0.8712 - val_loss: 0.3340
Epoch 21/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8710 - loss: 0.3356 - val_accuracy: 0.8714 - val_loss: 0.3339
Epoch 22/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8705 - loss: 0.3358 - val_accuracy: 0.8713 - val_loss: 0.3340
Epoch 23/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8715 - loss: 0.3350 - val_accuracy: 0.8711 - val_loss: 0.3352
Epoch 24/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8708 - loss: 0.3363 - val_accuracy: 0.8711 - val_loss: 0.3336
Epoch 25/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8712 - loss: 0.3361 - val_accuracy: 0.8714 - val_loss: 0.3336
Epoch 26/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8712 - loss: 0.3344 - val_accuracy: 0.8717 - val_loss: 0.3343
Epoch 27/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8706 - loss: 0.3350 - val_accuracy: 0.8710 - val_loss: 0.3336
Epoch 28/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8700 - loss: 0.3367 - val_accuracy: 0.8715 - val_loss: 0.3335
Epoch 29/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8698 - loss: 0.3375 - val_accuracy: 0.8713 - val_loss: 0.3345
Epoch 30/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8711 - loss: 0.3352 - val_accuracy: 0.8713 - val_loss: 0.3334

In [ ]:
from tensorflow.keras.layers import LSTM

model_lstm = Sequential([
    LSTM(32, input_shape=(1, X_train.shape[1])),
    Dense(1, activation='sigmoid')
])

model_lstm.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model_lstm.fit(
    X_train_rnn,
    y_train,
    epochs=30,
    batch_size=256,
    validation_split=0.2
)

Epoch 1/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.8550 - loss: 0.4107 - val_accuracy: 0.8701 - val_loss: 0.3385
Epoch 2/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8704 - loss: 0.3405 - val_accuracy: 0.8706 - val_loss: 0.3363
Epoch 3/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8708 - loss: 0.3370 - val_accuracy: 0.8712 - val_loss: 0.3352
Epoch 4/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8703 - loss: 0.3376 - val_accuracy: 0.8715 - val_loss: 0.3343
Epoch 5/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.8712 - loss: 0.3362 - val_accuracy: 0.8714 - val_loss: 0.3338
Epoch 6/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8711 - loss: 0.3365 - val_accuracy: 0.8714 - val_loss: 0.3338
Epoch 7/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8702 - loss: 0.3370 - val_accuracy: 0.8713 - val_loss: 0.3334
Epoch 8/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.8713 - loss: 0.3353 - val_accuracy: 0.8715 - val_loss: 0.3333
Epoch 9/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8718 - loss: 0.3343 - val_accuracy: 0.8715 - val_loss: 0.3334
Epoch 10/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8715 - loss: 0.3351 - val_accuracy: 0.8718 - val_loss: 0.3334
Epoch 11/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.8711 - loss: 0.3347 - val_accuracy: 0.8716 - val_loss: 0.3329
Epoch 12/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8715 - loss: 0.3362 - val_accuracy: 0.8717 - val_loss: 0.3330
Epoch 13/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.8707 - loss: 0.3361 - val_accuracy: 0.8712 - val_loss: 0.3332
Epoch 14/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8713 - loss: 0.3338 - val_accuracy: 0.8719 - val_loss: 0.3328
Epoch 15/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.8719 - loss: 0.3332 - val_accuracy: 0.8716 - val_loss: 0.3330
Epoch 16/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8711 - loss: 0.3342 - val_accuracy: 0.8714 - val_loss: 0.3330
Epoch 17/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.8710 - loss: 0.3351 - val_accuracy: 0.8717 - val_loss: 0.3331
Epoch 18/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8708 - loss: 0.3368 - val_accuracy: 0.8715 - val_loss: 0.3327
Epoch 19/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.8718 - loss: 0.3327 - val_accuracy: 0.8716 - val_loss: 0.3331
Epoch 20/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8716 - loss: 0.3337 - val_accuracy: 0.8717 - val_loss: 0.3333
Epoch 21/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.8720 - loss: 0.3329 - val_accuracy: 0.8716 - val_loss: 0.3329
Epoch 22/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8717 - loss: 0.3333 - val_accuracy: 0.8715 - val_loss: 0.3329
Epoch 23/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.8728 - loss: 0.3312 - val_accuracy: 0.8716 - val_loss: 0.3330
Epoch 24/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8715 - loss: 0.3332 - val_accuracy: 0.8717 - val_loss: 0.3330
Epoch 25/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.8727 - loss: 0.3314 - val_accuracy: 0.8719 - val_loss: 0.3326
Epoch 26/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8717 - loss: 0.3335 - val_accuracy: 0.8714 - val_loss: 0.3329
Epoch 27/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8713 - loss: 0.3332 - val_accuracy: 0.8714 - val_loss: 0.3334
Epoch 28/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8717 - loss: 0.3337 - val_accuracy: 0.8716 - val_loss: 0.3327
Epoch 29/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.8722 - loss: 0.3331 - val_accuracy: 0.8719 - val_loss: 0.3328
Epoch 30/30
1152/1152 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8718 - loss: 0.3324 - val_accuracy: 0.8718 - val_loss: 0.3329

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd
pred_ann_prob = model_ann.predict(X_test)
pred_ann = (pred_ann_prob > 0.5).astype(int)

ann_metrics = {
    "Accuracy": accuracy_score(y_test, pred_ann),
    "Precision": precision_score(y_test, pred_ann),
    "Recall": recall_score(y_test, pred_ann),
    "F1_score": f1_score(y_test, pred_ann),
    "ROC_AUC": roc_auc_score(y_test, pred_ann_prob)
}
pred_rnn_prob = model_rnn.predict(X_test_rnn)
pred_rnn = (pred_rnn_prob > 0.5).astype(int)

2880/2880 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step
2880/2880 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step

In [ ]:

rnn_metrics = {
    "Accuracy": accuracy_score(y_test, pred_rnn),
    "Precision": precision_score(y_test, pred_rnn),
    "Recall": recall_score(y_test, pred_rnn),
    "F1_score": f1_score(y_test, pred_rnn),
    "ROC_AUC": roc_auc_score(y_test, pred_rnn_prob)
}
pred_lstm_prob = model_lstm.predict(X_test_rnn)
pred_lstm = (pred_lstm_prob > 0.5).astype(int)

2880/2880 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step

In [ ]:

lstm_metrics = {
    "Accuracy": accuracy_score(y_test, pred_lstm),
    "Precision": precision_score(y_test, pred_lstm),
    "Recall": recall_score(y_test, pred_lstm),
    "F1_score": f1_score(y_test, pred_lstm),
    "ROC_AUC": roc_auc_score(y_test, pred_lstm_prob)
}

In [ ]:
metrics_df = pd.DataFrame({
    "ANN": ann_metrics,
    "RNN": rnn_metrics,
    "LSTM": lstm_metrics
})

print(metrics_df)

                ANN       RNN      LSTM
Accuracy   0.870994  0.870375  0.870581
Precision  0.766212  0.716444  0.713554
Recall     0.140797  0.154763  0.158634
F1_score   0.237882  0.254541  0.259563
ROC_AUC    0.777702  0.777388  0.779184